name: publish draft releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # Get tag name
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.MANTABOT_DOCKER_USERNAME }}
        password: ${{ secrets.MANTABOT_DOCKER_TOKEN }}

    - name: Set Tag env
      if: ${{ github.event.release.tag_name }}
      run: |
        echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> "$GITHUB_ENV"
        cp docker/calamari-pc .
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: docker/Dockerfile
        context: ${{ github.workspace }}
        tags: |
          linux6/calamari:latest
          linux6/calamari:${{ env.RELEASE_VERSION }}
        build-args: |
          TAG_NAME=${{ env.RELEASE_VERSION }}
          CALAMARI_PATH=${{ github.workspace }}
          COMMIT_HASH=${{ github.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
